version: "3"
services:
  master:
    image: hadoop-cluster
    hostname: master
    environment:
      - constraint:role==master
    ports:
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 50090:50090
      - 19888:19888
      - 8030:8030
      - 8031:8031
      - 8032:8032
      - 8033:8033
      - 8040:8040
      - 8088:8088
      - 8042:8042
      - 49707:49707
      - 2122:2122
    volumes: 
      - ./data:/home/data
      - ./code:/home/code
  worker:
    image: hadoop-cluster
    hostname: worker
    depends_on:
      - master
    environment:
      - constraint:role!=master
networks:
  default:
    driver: overlay
